version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/:/data/
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_PASSWORD=mypass
    - POSTGRES_USER=postgres
    ports:
      - 5432:5432
volumes:
    postgres_data: